version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54325:5432
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_USER: 'django'
      POSTGRES_PASSWORD: 'geekbrains'
      
  backend:
    build: 
      context: ./backend
    ports:
      - 8080:8080
    command: bash -c "
      .python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8080 --settings-backend.settings.debug"
    depends_on:
      - db
  
  frontend:
    build: path
