# Generated by Django 4.0.6 on 2022-08-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
    ]
